### ISSUE TITLE
Package for PyPI

### ISSUE THREAD

**Issue by kenbolton** [psolin/cleanco#1]
Seems like a good next step. If my tests with this software prove that it is a good fit for my project, I will gladly put in the work to push it up to PyPI.

**Comment by petri** [comment]
Yes, please make a PyPI release, this can be a very useful package to many people. It would be good to "upgrade" from distutils to setuptools prior to uploading to PyPI (btw there's a typo in the issue name). 

But it's not a necessity AFAIK.

@psolin, do you need help with PyPI release? Making a PyPI release is easy, really, though.

**Comment by psolin** [comment]
I haven't honestly looked into it, but I will soon.

**Comment by petri** [comment]
Ok. If you like, I can make the PyPI release as well, whichever you prefer (you'd still show up as the library author).

**Comment by petri** [comment]
As part of packaging, we should switch to setuptools from distutils for packaging.

**Comment by petri** [comment]
License added, made first release.
