### ISSUE TITLE
Move data away from main class (into country-specific modules?)

### ISSUE THREAD

**Issue by petri** [psolin/cleanco#11]
To support for example abbreviation expansion for other languages than english, it would be better if the data was split into submodules rathen than kept embedded in the class.

For example, add a "data" subpackage to contain language modules with names from the ISO 639-1 standard. So current ones would be in module "data/uk.py".

If this is ok, I can provide an implementation.

**Comment by psolin** [comment]
I agree, the data looks too crowded in the main code -- it takes up nearly half of the space.  I wanted to split it out a long time ago, but could never really figure out the correct way to do it.  I always envisioned a small sqlite file, but this might be a better way.  Anything you can do here will obviously be appreciated.

**Comment by petri** [comment]
Very well. Could you give me commit (write) rights to the repository (see repository settings)? That would perhaps speed up things a bit, given the time zone difference between us. As long as you keep the repository ownership to yourself, you can, if need be, always kick me out and undo any changes you don't like ;-)

**Comment by psolin** [comment]
You're on here, now.  Glad to have you on board.

**Comment by petri** [comment]
Thanks :)

**Comment by petri** [comment]
Done in 8f94096
