### ISSUE TITLE
stripping of suffix fails if it ends in full stop.

### ISSUE THREAD

**Issue by petri** [psolin/cleanco#21]
Same happens if the ending character is a comma. Example:

    >>> from cleanco import cleanco
    >>> y='posnegansett properties, llc.'
    >>> ya=cleanco(y)
    print ya.type()
    ['Limited Liability Company']
    >>> print ya.clean_name()
    posnegansett properties, llc

The result should not have the 'llc' suffix.

**Comment by psolin** [comment]
Fixed.
