### ISSUE TITLE
Cleanco not properly identifying Czech companies

### ISSUE THREAD

**Issue by jachymb** [psolin/cleanco#23]
Hello, thank you for your work on cleanco.

Cleanco does not seem to work properly for czech companies, eg:

```
>>> c = cleanco("Company s.r.o.")
>>> c.type() is None
True
>>> c.country() is None
True
>>> c = cleanco("Company a.s.")
>>> c.type() is None
True
>>> c.country() is None
True
```

Although I see that `'s.r.o.'` and `'a.s.'` are present in termdata.py in the right places.

One more detail, there is also the possibility to use `'spol. s r.o.'` instead of `'s.r.o.'` in Czech Republic - they are equivalent. `'spol. s r.o.'` is not present in termdata.py.

**Comment by petri** [comment]
It seems c.clean_name() also fails:

```
>>> c.clean_name()
'Company s.r.o'
```

**Comment by petri** [comment]
Fix merged.
