### ISSUE TITLE
Could we please have 1.4 or 1.3.1 (or any release) in PyPI With the recent patches?

### ISSUE THREAD

**Issue by jachymb** [psolin/cleanco#30]

**Comment by psolin** [comment]
@petri has access to this (I do not).

**Comment by petri** [comment]
I can cut a release. See https://github.com/psolin/cleanco/milestone/2 ; @psolin if there are any issues you think we should & can include to the release (I have no time to work on any), feel free to add them to milestone. Alternatively, I can just cut a release of what's in master now.

**Comment by petri** [comment]
Taking a look at the issues, I think we should get rid of the tabs finally, ie. issue #16 .

**Comment by petri** [comment]
@jachymb sorry for the long delay, we should've cut an interim release to PyPI long ago. The 2.0 improvements have been committed. We need to test it a bit more & will cut a fresh release after that.

**Comment by petri** [comment]
All the fixes that I can think of that should absolutely be there to declare 2.0 ready for release are now committed. Tests have been updated. Unless something new comes up I think we can release 2.0 @psolin right?

**Comment by psolin** [comment]
That works. Thanks petri!

**Comment by petri** [comment]
Released 2.0.0 and 2.0.1 (incorporated README.md into PyPI package page)
