### ISSUE TITLE
Croatian companies

### ISSUE THREAD

**Issue by dstipanovic** [psolin/cleanco#35]
I minor thing:

'Croatia': ['d.d.', 'd.d.o.', 'obrt'],

should be:

'Croatia': ['d.d.', 'd.o.o.', 'obrt'],

d.o.o = "drustvo ogranicene odgovornosti"; there is no d.d.o (but d.d. is OK, as it stands for  "dionicko drustvo")

**Comment by psolin** [comment]
Fixed.
