### ISSUE TITLE
Not Working for 'p.c.

### ISSUE THREAD

**Issue by chakravarthych** [psolin/cleanco#36]
i am trying to parse a business name which contains p.c. as an extension, but when i try to use x.type() it returns none type object

Ex:-

cleanco(dentistry   for children, louis a. pollina, d.d.s., p.c.)
x.type()
Returns none
--

**Comment by psolin** [comment]
This works. See below:

>>> from cleanco import cleanco
>>> business_name = "dentistry for children, louis a. pollina, d.d.s., p.c." 
>>> x = cleanco(business_name)
>>> x.type()
['Professional Corporation']
