### ISSUE TITLE
country logic does not work for terms ending with '.'

### ISSUE THREAD

**Issue by murphd40** [psolin/cleanco#40]
```python
business_name = "Some Big Pharma sh.a."
x = cleanco(business_name)

print(x.business_name)
print(x.string_stripper(x.business_name))
print(x.clean_name())
print(x.country())
```

prints:

```
Some Big Pharma sh.a.
Some Big Pharma sh.a
Some Big Pharma
None
```

---

`sh.a.` is in the `Albania` terms:

https://github.com/psolin/cleanco/blob/56ff6542c339df625adcaf7f4ed4c81035fd575a/termdata.py#L46

It is not being recognized as Albanian because the `.` at the end of `sh.a.` is removed in:

https://github.com/psolin/cleanco/blob/56ff6542c339df625adcaf7f4ed4c81035fd575a/cleanco.py#L56

**Comment by psolin** [comment]
Yes, absolutely. I need to spend more time cleaning this up for sure.
