### ISSUE TITLE
SRL missing

### ISSUE THREAD

**Issue by MeliBall** [psolin/cleanco#42]
Hi guys
fantastic job.. but one important ending is missing: "SRL" without final dot 
name = cleanco("Unimarkt Handelsgesellschaft SRL").clean_name(prefix=True, suffix=True, middle=True, multi=True)
print(name)
output
Unimarkt Handelsgesellschaft SRL

**Comment by petri** [comment]
Fixed in 4c102975b30610c022e777693d3adb891d5f9332, closing.
