### ISSUE TITLE
error in Belgium

### ISSUE THREAD

**Issue by MeliBall** [psolin/cleanco#44]
HI Guys

there is an error in one of the belgium types: 
the correct type is  CVBA: coöperatieve vennootschap met beperkte aansprakelijkheid (CVBA)

However in your covered terms it is written as "'cbva'"
https://pydoc.net/cleanco/1.3/termdata/

thanks !

**Comment by petri** [comment]
Thank you. This seems to be a valid correction.

**Comment by petri** [comment]
Fixed in 4c102975b30610c022e777693d3adb891d5f9332, closing
