### ISSUE TITLE
Estonian entity types mostly missing

### ISSUE THREAD

**Issue by mklopets** [psolin/cleanco#58]
[Estonian legal entity types](https://en.wikipedia.org/wiki/List_of_legal_entity_types_by_country#Estonia) such as OÜ, MTÜ, AS, UÜ, TÜ are missing – only FIE seems to be supported.

Could try adding them myself – is `termdata.py` the only place that needs to have these added in?

**Comment by petri** [comment]
It is. You might also want to take a look at the https://pypi.org/project/iso-20275 package. The plan is to use data from there and just augment it when it's missing some types etc.

**Comment by petri** [comment]
OÜ and AS were just added. Pull request welcome.
