### ISSUE TITLE
Add support for case, whitespace & separator normalization

### ISSUE THREAD

**Issue by petri** [psolin/cleanco#6]
I understand this may fall outside the scope, but it would be very convenient if cleanco also had this kind of simple normalization built-in:

- standardizing lettercase (e.g., all lowercase)
- standardizing separators (e.g., commas must be followed by spaces)
- standardizing whitespace (e.g., converting all runs of whitespace to single spaces)

**Comment by psolin** [comment]
* standardizing lettercase (e.g., all lowercase)
I disagree.  Some companies have odd capitalization, so it is probably best to leave this as-is.  Anyone can choose to use the .lower() function later if they want to.

* standardizing separators (e.g., commas must be followed by spaces)
This might be a good idea, but I want to think about it (why add something if it breaks other things in the future)

* standardizing whitespace (e.g., converting all runs of whitespace to single spaces)
The code already does this:

 > business_name = " ".join(business_name.split())

**Comment by petri** [comment]
To clarify, I meant these to be optional convenience features rather than changing existing behavior - and yes, I did not realize the extra whitespace removal was already there, that's nice.

**Comment by petri** [comment]
Thinking a bit more about this, the only remaining part of the request (separator normalization) is not really that important, and having lowercase name is trivial so I feel we can close this.
