### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by danielchiu** [psolin/cleanco#60]
The non-determinism was fixed in #54 in June, but the latest release (2.0.1) was in April. Is it possible to release a version fixing the non-determinism?

**Comment by twalen** [comment]
I'm also strongly interested in new release.

**Comment by petri** [comment]
I'm happy to build & push a release to PyPI if someone can submit a release PR (with setup.py, CHANGES.txt etc. changes). We should also drop old Python versions & switch away from Travis to Github CI actions.

**Comment by petri** [comment]
Many of the things were done in #62. @twalen could you update the changelog with what's changed since 2.0.1? I will then cut a release.

**Comment by twalen** [comment]
Thank you very much! I will update the changelog shortly.

**Comment by twalen** [comment]
@petri I've updated changes.txt file in the pull request:  #63

**Comment by petri** [comment]
Done.
