### ISSUE TITLE
prepare_terms() should be part of base_name()

### ISSUE THREAD

**Issue by taraskuzyk** [psolin/cleanco#70]
This probably breaks the scope of abstraction. If I want to get a clean name of the company, I shouldn't care about this implementation detail. 

Also makes the function more readable - it is intuitive that I should put in company_name into base_name function to get a base name of the company name

Heuristic more than anything but maybe somebody finds this important enough to fix

**Comment by petri** [comment]
#75 was merged that should fix this issue. Thank you @taraskuzyk for raising this issue and taking the time to provide a PR.
