### ISSUE TITLE
 suffixes missing :S.A. DE C.V. 

### ISSUE THREAD

**Issue by dolphin-Jia** [psolin/cleanco#76]
you miss a suffixes: S.A. DE C.V. 
please add it ,thanks

**Comment by FBnil** [comment]
Thanks for reporting. That one should go under Mexico.

`'Mexico': ['s.a.', 's. de. r.l.', 's. en c.', 's.a.b.', 's.a.p.i.', 's.a. de c.v.'],`

Will offer a pull later this month.

**Comment by petri** [comment]
added
