### ISSUE TITLE
Importing version 2.2 fails

### ISSUE THREAD

**Issue by aafendi** [psolin/cleanco#78]
I have this issue on multiple python versions, running on databricks. (This shouldn't be a problem tho)
Cleanco version 2.2 won't import. However, cleanco version 2.1 works and I've rolled back all my jobs to that.

`ImportError: cannot import name 'cleanco' from 'cleanco'`

Cluster1:
- OS: Ubuntu 18.04.5 LTS
- Python version: 3.7.5

Cluster2:
- OS:  Ubuntu 20.04.3 LTS
- Python version: 3.8.8

**Comment by petri** [comment]
You're using the old class based API that has been deprecated. See docs on current API.
