### ISSUE TITLE
GMBH

### ISSUE THREAD

**Issue by rorymullen** [psolin/cleanco#89]
This package doesn't seem to be working on the German GMBH

**Comment by ronarbo** [comment]
Seems to be working for me at least for simple examples:

```python
[ins] In [4]: basename("foot GMBH")                                                                            
Out[4]: 'foot'

[ins] In [5]: basename("foot gmbh")                                                                            
Out[5]: 'foot'
```

**Comment by rorymullen** [comment]
Thanks ronarbo, it was entirely my mistake, I had one case of G M B H, which, I suppose, the package would not pick up, and I had another case that was resolved by running basename() twice, as the documentation suggests. My apologies for not marking this as resolved, and thanks again for looking into this.
